apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    path: 'my-web-app'
  project: default
