apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app
spec:
  destination:
    server: 'https://10.22.70.190:6443'
    namespace: default
  source:
    repoURL: 'https://github.com/Mamatha-Reddy-24/GitOps_ArgoCD_local.git'
    path: 'my-web-app'
  project: default
